# -*- coding: utf-8 -*-
"""Despliegue-Diabetes-Binary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bcpfkq4ijXEjVDoDpY_9xExXBGvZ94a6
"""

import pickle
import pandas as pd

filename = 'modelo-cla -diabetes.pkl'

modelo, encoder, variables, scaler = pickle.load(open(filename, 'rb'))

#Interfaz gráfica
#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.title('Sistema de Predicción de Diabetes')

BMI = st.slider('BMI', min_value=0.0, max_value=70.0, value=25.0, step=0.1)

MentHlth = st.slider('Mental Health', 0, 30, 0)

PhysHlth = st.slider('Physical Health', 0, 30, 0)

GenHlth = st.selectbox('General Health',
                       [1,2,3,4,5])

Age = st.selectbox('Age',
                   [1,2,3,4,5,6,7,8,9,10,11,12,13])

Education = st.selectbox('Education',
                         [1,2,3,4,5,6])

Income = st.selectbox('Income',
                      [1,2,3,4,5,6,7,8])

HighBP = st.selectbox('High Blood Pressure',
                      [0,1])

HighChol = st.selectbox('High Cholesterol',
                        [0,1])

Smoker = st.selectbox('Smoker',
                      [0,1])

Stroke = st.selectbox('Stroke',
                      [0,1])

PhysActivity = st.selectbox('Physical Activity',
                            [0,1])

Fruits = st.selectbox('Fruits',
                      [0,1])

Veggies = st.selectbox('Veggies',
                       [0,1])

Sex = st.selectbox('Sex',
                   [0,1])

BMI = 25.0
MentHlth = 5
PhysHlth = 3
GenHlth = 2
Age = 5
Education = 4
Income = 6
HighBP = 1
HighChol = 0
Smoker = 0
Stroke = 0
PhysActivity = 1
Fruits = 1
Veggies = 1
Sex = 1

# Crear diccionario con todas las variables en 0

data_dict = {col:0 for col in variables}

# Variables numéricas
data_dict['BMI'] = BMI
data_dict['MentHlth'] = MentHlth
data_dict['PhysHlth'] = PhysHlth

# Variables categóricas
data_dict[f'GenHlth_{GenHlth}'] = 1
data_dict[f'Age_{Age}'] = 1
data_dict[f'Education_{Education}'] = 1
data_dict[f'Income_{Income}'] = 1

# Variables binarias
data_dict['HighBP_1'] = HighBP
data_dict['HighChol_1'] = HighChol
data_dict['Smoker_1'] = Smoker
data_dict['Stroke_1'] = Stroke
data_dict['PhysActivity_1'] = PhysActivity
data_dict['Fruits_1'] = Fruits
data_dict['Veggies_1'] = Veggies
data_dict['Sex_1'] = Sex

# Crear dataframe
data = pd.DataFrame([data_dict])

prediccion = modelo.predict(data)

if prediccion[0] == 1:
    st.error('El paciente puede tener diabetes')
else:
    st.success('El paciente no presenta diabetes')

st.warning("El modelo XGBoost tiene una precisión del 83.7%")